### PR TITLE
Added support for PHP8

### PR DESCRIPTION
**Pull request by einar-hansen**
Adds support for PHP8. Tested on PHP7.4.14 and PHP8.0.1.

### CODE REVIEW

**Comment by einar-hansen** [comment]
So, in addition to modify the composer.json file we need to use the getIterator method instead of rewind() for PHP8. Otherwise you'll get a `BadMethodCallException`with the message: "rewind" has been removed on PHP8, use ::getIterator() in place.

**Comment by adamwojs** [comment]
Hi @einar-johan, thank you for PR. I will take a look on this today :wink:

**Comment by adamwojs** [comment]
I'm really sorry that it take so long from my side. The only comment is that we don't need `->getIterator()` calls in PHP 8, so patch could be simplified to https://github.com/adamwojs/php-cs-fixer-phpdoc-force-fqcn/pull/11

**Comment by adamwojs** [comment]
Closed in favour of #11

**Pull request closed without merging**
